version: '3'
services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
    command: npm run dev

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
    stdin_open: true
    command: npm start
