name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and Test Server
        run: |
          cd server
          npm install
          npm run build
      - name: Install and Test Client
        run: |
          cd client
          npm install
          npm run build
